In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.shape

(3,)

In [6]:
a1.ndim

1

In [7]:
type(a2)

numpy.ndarray

In [8]:
a2.shape

(2, 3)

In [9]:
a2.ndim

2

In [10]:
import pandas as pd

In [11]:
df=pd.DataFrame(a1)
df

0
0  1
1  2
2  3

Creating NumPy Arrays

In [1]:
import numpy as np

In [2]:
ones=np.ones((2,3))

In [3]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
ones.dtype

dtype('float64')

In [6]:
ones.dtype

dtype('float64')

In [9]:
range_array=np.arange(0,12,1)
range_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
random_array=np.random.randint(0,10,size=(2,3))
random_array

array([[2, 1, 8],
       [9, 9, 9]])

In [12]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.1584885 , 0.88970674, 0.1860627 ],
       [0.76051578, 0.48058039, 0.75088324],
       [0.93157324, 0.63387753, 0.52938901],
       [0.47911523, 0.01216424, 0.34040719],
       [0.51236759, 0.46095711, 0.2783215 ]])

In [26]:
np.random.seed(9999)
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [29]:
np.random.seed(0)
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [30]:
np.random.seed(7)
random_array_3=np.random.rand(1,3)
random_array_3

array([[0.07630829, 0.77991879, 0.43840923]])

In [31]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[7, 7, 9, 7, 8],
         [9, 8, 7, 6, 4],
         [0, 7, 0, 7, 6],
         [3, 5, 8, 8, 7]],

        [[5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0],
         [1, 0, 0, 6, 7]],

        [[7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5]]],


       [[[9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5],
         [3, 0, 4, 8, 6]],

        [[7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2]],

        [[6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9],
         [7, 5, 4, 9, 6]]]])

In [34]:
a4[:,:,:,1]

array([[[7, 8, 7, 5],
        [0, 6, 3, 0],
        [9, 7, 1, 3]],

       [[1, 5, 9, 0],
        [2, 6, 1, 9],
        [8, 1, 8, 5]]])

In [7]:
##Manipulating data2
import numpy as np

In [4]:
ab=np.random.random(20)
ab

array([0.17365468, 0.78650391, 0.92460541, 0.50508361, 0.04675145,
       0.03932451, 0.13275892, 0.81323095, 0.00523042, 0.05723184,
       0.29877755, 0.06133347, 0.64357812, 0.24311013, 0.59510148,
       0.95516569, 0.81848437, 0.04549468, 0.14836421, 0.63958436])

In [5]:
%timeit sum(ab)
%timeit np.sum(ab)

9.54 µs ± 942 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
7.52 µs ± 514 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
np.mean(a1)

NameError: name 'a1' is not defined

In [9]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [10]:
np.mean(a1)

2.0

In [11]:
np.max(a1)

3

In [12]:
np.min(a1)

1

In [13]:
np.std(a1)

0.816496580927726

In [14]:
np.var(a1)

0.6666666666666666

In [15]:
np.sqrt(np.var(a1))

0.816496580927726

In [1]:
import numpy as np

In [3]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a2.shape

(2, 3)

In [5]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [6]:
a2.reshape(2,3,1).shape

(2, 3, 1)

DOT PRODUCT

In [11]:
np.random.seed(0)
mat1=np.random.randint(10,size=(3,2))
mat2=np.random.randint(10,size=(3,2))

In [12]:
mat1

array([[5, 0],
       [3, 3],
       [7, 9]])

In [13]:
mat2

array([[3, 5],
       [2, 4],
       [7, 6]])

In [14]:
#Element wise
mat1*mat2

array([[15,  0],
       [ 6, 12],
       [49, 54]])

In [18]:
#Dot wise
np.dot(mat1,mat2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [29]:
mat1.shape, mat2.T.shape

((3, 2), (2, 3))

In [31]:
mat3=np.dot(mat1, mat2.T)
mat3

array([[ 15,  10,  35],
       [ 24,  18,  39],
       [ 66,  50, 103]])

In [32]:
mat3.shape

(3, 3)

 SORTING AN ARRAY 

In [53]:
arr=np.random.randint(10, size=(2,4))
arr

array([[5, 9, 8, 9],
       [4, 3, 0, 3]])

In [54]:
np.sort(arr)

array([[5, 8, 9, 9],
       [0, 3, 3, 4]])

In [55]:
#argsort gives the index from least to high number
np.argsort(arr)

array([[0, 2, 1, 3],
       [2, 1, 3, 0]], dtype=int64)

In [45]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [46]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [47]:
np.argmin(a1)

0

In [48]:
np.argmax(a1)

2

In [50]:
np.argmax(arr, axis=0)

array([0, 0, 1, 0], dtype=int64)

In [51]:
arr

array([[8, 8, 1, 6],
       [7, 7, 8, 1]])

In [52]:
np.argmax(arr, axis=1)

array([0, 2], dtype=int64)

DOT PRODUCT EXAMPLE(NUT BUTTER SALES) 

In [5]:
import numpy as np


In [6]:
np.random.seed(0)
sales_amt=np.random.randint(20,size=(5,3))
sales_amt

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [7]:
import pandas as pd

In [8]:
weekly_sales=pd.DataFrame(sales_amt,
                         index=["Mon","Tue","wed","Thur","Fri"],
                         columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tue               3              3              7
wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [9]:
prices=np.array([12,13,14]) 
prices

array([12, 13, 14])

In [11]:
butter_prices=pd.DataFrame(prices.reshape(1, 3),
                          index=["Price"],
                          columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             12             13             14

In [12]:
 prices.shape

(3,)

In [17]:
sales_amt.shape

(5, 3)

In [19]:
total_sales=prices.dot(sales_amt)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [20]:
total_sales=prices.dot(sales_amt.T)
total_sales

array([339, 173, 607, 294, 188])

In [21]:
 weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [22]:
daily_sales=butter_prices.dot(weekly_sales.T)

In [23]:
daily_sales

Mon  Tue  wed  Thur  Fri
Price  339  173  607   294  188

In [25]:
#donest work not the crt shape
weekly_sales["Total($)"]=daily_sales
weekly_sales

ValueError: Wrong number of items passed 5, placement implies 1

In [26]:
weekly_sales.shape, daily_sales.shape

((5, 3), (1, 5))

In [29]:
weekly_sales["Total($)"]=daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total($)
Mon              12             15              0       339
Tue               3              3              7       173
wed               9             19             18       607
Thur              4              6             12       294
Fri               1              6              7       188

# TURN IMAGE INTO NUMPY ARRAY

In [2]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
<img src="images/girls.png"/>

SyntaxError: invalid syntax (<ipython-input-5-86d90c5e431e>, line 1)

In [1]:
from matplotlib.image import imread